version: '3'
services:

  postgres:
    container_name: postgres
    restart: always
    build:
      context: ./db
    volumes:
      - "./db/data/:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # To be moved to environment file
      POSTGRES_DATABASE: centripetal
    expose:
      - 5432
    ports:
      - 2345:5432
    networks:
      - postgres-postgraphile

  postgraphile:
    container_name: postgraphile
    restart: always
    image: graphile/postgraphile
    depends_on:
      - postgres
    expose:
      - 5000
    ports:
      - 5000:5000
    command: ["postgraphile", "--connection", "postgres://cp_postgraphile:some-decent-password@db/centripetal", "--host", "localhost", "--port", "5000", "--schema", "app_public"]
    links:
      - postgres
    networks:
      - postgres-postgraphile

networks:
  postgres-postgraphile:
