version: '3'
services:

  db:
    container_name: psql
    restart: always
    build:
      context: ./db
    volumes:
      - "./db/data/:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # To be moved to environment file
      POSTGRES_DATABASE: centripetal
    expose:
      - 5432
    ports:
      - 2345:5432
    networks:
      - psql-pgql

  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://cp_postgraphile:some-decent-password@localhost:2345/centripetal
    expose:
      - 5000
    ports:
      - 5000:5000
    command: ["postgraphile", "--connection", "postgres://cp_postgraphile:some-decent-password@db:5432/centripetal", "--host", "localhost", "--port", "5000", "--schema", "app_public"]
    links:
      - db
    networks:
      - psql-pgql

networks:
  psql-pgql:
